# Regenerate figures from a completed Step 2 overview; never starts a simulation.
args <- commandArgs(trailingOnly=TRUE)
if (!length(args)) stop("Usage: Rscript scripts/rebuild_gallery.R exact_overview.rds [case_file]")
suppressPackageStartupMessages({library(dplyr);library(tidyr);library(tibble);library(purrr);library(ggplot2)})
source("R/workflow_config.R");source("R/workflow_functions.R")
e <- smart31_workflow_functions("step2")
e$.smart31_case <- smart31_load_case(if(length(args)>1L) args[[2L]] else "config/case_study.R")
e$.smart31_years <- smart31_year_values(e$.smart31_case)
e$cfg <- smart31_stage_config(e$.smart31_case,"step2")
path <- normalizePath(args[[1L]],mustWork=TRUE)
bundle <- readRDS(path)
smart31_validate_step2_policy(bundle,e$.smart31_case)
result <- e$smart31_archive_render_report(bundle,dirname(path),reuse_existing=FALSE)
print(result$report_file)
